FROM alpine:latest
RUN apk update
RUN apk add nginx
RUN apk add git
RUN rm -rf /var/cache/apk/*
#RUN touch -R /run/nginx/nginx.pid
COPY default.conf /etc/nginx/http.d/default.conf


RUN git clone https://github.com/veekrum/task.git /tmp/task
RUN mv /tmp/task/site/ /usr/share/nginx/html
RUN chown -R nginx:nginx /usr/share/nginx/html/site/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
